FIX subprocess call for Windows
harper25/poetry-poems pull request #9
Opened 2021-03-11 19:17 UTC by pjarnhus

The call made with subprocess.POpen all used shell=False. This works on
Linux and mac, but is an issue on Windows. In this case Windows expects
a full string to the executable. The code only provides a shell command,
and we should set shell=True for Windows.

This has the drawback, that if ever an explicit string command is used,
the logic needs to be refined.

2021-03-12 19:11 UTC, harper25 commented
Travis CI is failing due to formatting (logs): https://github.com/harper25/poetry-poems/blob/master/docs/contributing.rst#linter (or https://poetry-poems.readthedocs.io/en/latest/contributing.html#linter). Could you please run these formatting tools? Also, could you please elaborate on "This has the drawback, that if ever an explicit string command is used, the logic needs to be refined.". I am not sure I get it.

2021-03-30 19:11 UTC, pjarnhus commented
You are quite right, that the wording was not very good for the last bit. That is mainly due to my limited understanding of the subprocess module. Based on this [SO post](https://stackoverflow.com/questions/3172470/actual-meaning-of-shell-true-in-subprocess), I have tried to update the commit message.

It could be that the change should be made with a try-catch instead, so that we do not go directly to `shell=True` on a Windows system, but only if a FileNotFoundError exception is raised...

2021-04-06 17:36 UTC, pjarnhus commented
I keep getting a failure on black, even though I ran black on the entire codebase... Is it set up with a non-standard config, that I am completely missing?

2021-04-08 17:49 UTC, harper25 commented
This is definitely a tricky thing... Generally it is not advised to use `shell=True`, but it may be inevitable here.

A few ideas before moving on with merging:
- for old version and bugfix version debug into subprocess (debugger or prints) to see what are `executable` and `args` in 
```
File "c:\users\phrj\miniconda3\lib\subprocess.py", line 1307, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
```
- try adding Python to Windows path (also try running python --version, poetry --version, poems --version to see if poetry is visible), if it is not a big deal with Anaconda
- for Windows platform try using `cmds = shlex.join(cmds)` with `shell=False` in PipedPopen() to invoke Popen with one concatenated string instead of a list of strings (https://docs.python.org/3/library/shlex.html#shlex.join)
- for Mingw I noticed that there is a special utility to communicate with the cmd.exe and instead of invoking `poems` it is required to run `winpty poems` (https://stackoverflow.com/questions/48199794/winpty-and-git-bash). Maybe this will help for the old version of poems?

If none of the above works, then let's add try/except inside PipedPopen() in order not to do `shell=True` for all Windows users.

2021-04-08 17:57 UTC, harper25 commented
Regarding black, the config is located in pyproject.toml under `[tool.black]`. Not sure, why it is not working...

2021-05-23 16:23 UTC, harper25 requested changes
Recently I reinstalled Windows10 and started to have the same issue. So, my proposition is just to make the pipeline green and merge (no other changes in the code), how about that?
I need this change for my next MR for Win.

Regarding subprocess.py (tested out of curiosity):

```
File "c:\users\phrj\miniconda3\lib\subprocess.py", line 1307, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
```

- old version:
```
executable: None
args: poetry config virtualenvs.path
```

- bugfix version:
```
executable: None
args: C:\WINDOWS\system32\cmd.exe /c "poetry config virtualenvs.path"
```

2021-05-23 16:23 UTC, harper25 commented on poetry_poems/picker/__init__.py
> +            data = json.dumps({"query": self.query, "envs": len(self.environments),})
Please, revert this formatting change to make the pipeline pass.

2021-05-23 16:23 UTC, harper25 commented on tests/unit/test_utils.py
> +    "query,num_results", [("proj", 2), ("proj1", 1), ("o", 4), ("zzz", 0),],
Please, revert this formatting change to make the pipeline pass.

2021-06-04 16:07 UTC, harper25 commented
Regarding black it is possible to specify a path to a config file, maybe this will help:
`black --config pyproject.toml .`
My version of black is: `black, version 20.8b1`

2021-06-05 13:55 UTC, merged

2021-06-05 14:16 UTC, harper25 commented
Merged, thanks a lot for reporting the issue and contribution!

2021-06-05 14:26 UTC, pjarnhus commented
You're are welcome! Thank you for helping me getting it across the line. Life did not leave much time for hobby projects over the last couple of months.

2021-06-05 18:16 UTC, harper25 commented
No problem, feel free to add new things when the time allows for that 👍

2021-06-05 18:21 UTC, harper25 commented
Issue link: https://github.com/harper25/poetry-poems/issues/8